### ISSUE TITLE
store robbery

### ISSUE THREAD

**Issue by dexslab** [LADOJRP/server#100]
Every 24/7 I’ve been too when you try to rob the store it says there must be at least 2 LEO in town to rob and there’s always like 10 LEO on so I’ve been having to make 911 calls about the robbery.

---
This issue was created by `@Gator` in `#server-issues`.

**Comment by urban-z** [comment]
We need to add the jobs to the script for it calculate properly.

**Comment by dexslab** [comment]
script is esx_holdup in [esx-legacy] folder

**Comment by dexslab** [comment]
just fixed this issue
