### ISSUE TITLE
Storage/stash to high

### ISSUE THREAD

**Issue by dexslab** [LADOJRP/server#115]
the storage/stash at 3021 is way to high and you can not open it

---
This issue was created by `@noneedtostop` in `#server-issues`.

**Comment by urban-z** [comment]
Marker is on ground.. actually appears to be too low

![image](https://github.com/LADOJRP/server/assets/129465098/e56c39f3-8a8d-4e49-96cb-92b7e66bfe0b)

**Comment by dexslab** [comment]
can you access the stash with F3 as i think the distance for interaction is set to 2m

**Comment by dexslab** [comment]
fixed for next restart
