### ISSUE TITLE
/Onduty not working

### ISSUE THREAD

**Issue by dexslab** [LADOJRP/server#121]
Myself and a few lapd officers have tried to go on duty and nothing comes up when we do /onduty lapd unsure if lasd works.

---
This issue was created by `@DaveB` in `#server-issues`.

**Comment by urban-z** [comment]
@dexslab this has been fixed and is in a pending pull request.  It was a missing comma in the ox_inventory items file from DaPickle's update

**Comment by urban-z** [comment]
was issue with Ox Inventory. fixed earlier today
