### ISSUE TITLE
OX Inventory F8 ERRORS

### ISSUE THREAD

**Issue by dexslab** [LADOJRP/server#123]
The OX Inventory system is throwing errors -- lots of them from teh new addition from 3 daysa ago

---
This issue was created by `@Urban Zook` in `#server-issues`.

**Comment by urban-z** [comment]
[    317172] [b2802_GTAProce]             MainThrd/ ^1SCRIPT ERROR: @ox_inventory/data/items.lua:1459: '}' expected (to close '{' at line 1453) near 'client'^7
[    317172] [b2802_GTAProce]             MainThrd/ ^3> fn^7 (^5@ox_inventory/modules/init.lua^7:110)

**Comment by urban-z** [comment]
@dexslab this has been fixed and is in a pending pull request.  It was a missing comma in the ox_inventory items file from DaPickle's update

**Comment by urban-z** [comment]
resolved
