### ISSUE TITLE
Towing Gator

### ISSUE THREAD

**Issue by dexslab** [LADOJRP/server#125]
When using code3trailer2 and code3 gator, the Gator will attach [/tow] to the most rearside of the trailer. Does not look match appropraite RP and trailer teathers. Staff was brought via /report and could not resolve immediately either; suggested ticket here.

---
This issue was created by `@Rbebout313` in `#server-issues`.

**Comment by urban-z** [comment]
You must use the /attach command and not the /tow command to attach the Gator to the Code3 Trailer.
