### ISSUE TITLE
Oxygen EUP

### ISSUE THREAD

**Issue by dexslab** [LADOJRP/server#126]
When you put the tank #123 in MP Ped it falls off and thats normal the only issue i have is a white or blue shirt shows up when it falls off not to sure if that can be fix or not just thought id make you guy aware to attempt to fix it

---
This issue was created by `@Chris R` in `#server-issues`.

**Comment by urban-z** [comment]
@JimmyMccann

**Comment by JimmyMccann** [comment]
This Oxygen tank is base game made for water activity which means there is nothing i can do to stop it from falling off when you are out of water
