### ISSUE TITLE
Spawning in SSPD Cell

### ISSUE THREAD

**Issue by dexslab** [LADOJRP/server#128]
When pressing K while unconsious, it spawns you in SSP Cell #3

---
This issue was created by `@Reid` in `#server-issues`.

**Comment by urban-z** [comment]
The issue is with the Medical Script Respawn.

I dont know the script name.

**Comment by urban-z** [comment]
This has been resolved.  Will respawn in Sandy Hospital

**Comment by urban-z** [comment]
Done
