### ISSUE TITLE
Bringing back /bm [In chat black market]

### ISSUE THREAD

**Issue by harrysingh98** [LADOJRP/server#13]
Add back /bm [Message] for blackmarket with a 60 second timeout. If you use /bm you cannot use it again untilt he 60 seconds are over.

**Comment by harrysingh98** [comment]
**Not visible to onduty leo or fire

**Comment by dexslab** [comment]
> **Not visible to onduty leo or fire

Fine i will make it even more awesome

**Comment by dexslab** [comment]
This complete just need to make some message template changes will do that and make it even more awesome soon
