### ISSUE TITLE
Drift Mode

### ISSUE THREAD

**Issue by dexslab** [LADOJRP/server#130]
It is wonky now, whenever using it, it’s slow doesn’t really allow you to drift and such. Out of no where you cannot control it but a month ago we were actually able to control where we drift and how it looks. Now it just goes straight and is stuck

---
This issue was created by `@Austin` in `#server-issues`.

**Comment by urban-z** [comment]
@bigdevryan sounds like a handling issue. Unless we have a drift script..

**Comment by bigdevryan** [comment]
> @bigdevryan sounds like a handling issue. Unless we have a drift script..

It's vMenu drift mode. Dex is the only one that messes with vMenu to my knowledge

**Comment by dexslab** [comment]
Yes but havent messed with drift mode i dont think we will fix this issue
