### ISSUE TITLE
Broken onduty/offduty

### ISSUE THREAD

**Issue by dexslab** [LADOJRP/server#138]
When in server, I am locked on duty but unable to access radio frequencies or recieve the equipment one would have on duty, but I am able to unlock doors as the script is detecting im on duty, I just can't do everything I need to do while on duty. The easy solution would be to go offduty and both onduty, but then it says im not on duty, and if I try to go on duty it says im already on duty, and it is an endless cycle.

---
This issue was created by `@Gekko` in `#server-issues`.

**Comment by urban-z** [comment]
User need to do /stopjob.

job was stock.. now resolved
