### ISSUE TITLE
Implement Property system where you can buy furniture inside bought property from city hall (gives people motive to grind money)

### ISSUE THREAD

**Issue by bigdevryan** [LADOJRP/server#142]
@urban-z

**Comment by urban-z** [comment]
- Added files to server
- Added configs for webhooks to discord logs
- Added category and new channels in LADOJ Logs
- Requested SQL to be ran on DB

**Comment by urban-z** [comment]
Finalized initial properties.. 

testing completed

need to work with owners to get their IRL properties back

need to discuss buying more shells
