### ISSUE TITLE
Make a bank robbery script (add lock picks) 

### ISSUE THREAD

**Issue by bigdevryan** [LADOJRP/server#144]

**Comment by urban-z** [comment]
- Add scripts
- Added logs to pacific standard script
- updated laptop hack to 300 word list to chose from
- reduced prices


PENDING:
- populate pacific standard with peds
- move start and end locations (too many people know)
- fix logging issue when finishing the job -- not logging to discord. doesnt seem like it hits event.

**Comment by dexslab** [comment]
@urban-z  can we get an update on this

**Comment by urban-z** [comment]
Interiors are in production to test for crashing. So far so good. Next week will test script with staff team in dev server.
