### ISSUE TITLE
Make it to where you have to go to city hall to pick a job (get rid of the /startjob command (fix the jobs)

### ISSUE THREAD

**Issue by bigdevryan** [LADOJRP/server#146]

**Comment by dexslab** [comment]
Is done should be in for restart

**Comment by urban-z** [comment]
We need to check the issue where it isnt restricting their jobs.  If they pick a job, they can still go do any other job with no issues. it should restrict them and make them go back to City Hall and pick that job.. and it shouldnt show the blip unless they are employed for that job
