### ISSUE TITLE
Drug script update

### ISSUE THREAD

**Issue by bigdevryan** [LADOJRP/server#153]
if you sell drugs to NPC's they had a script where (40% chance it will tell you to fuck off - 40% it will buy the drugs from you - 20% it will call the cops on you). That would be sick. Also an implementation if the AI who calls the cop could take a picture of their face and send it into some sort of database where LEO can view it. People will be forced to wear masks doing illegal activities.

**Comment by urban-z** [comment]
Drug script part done
notify cops done
picture of person selling - not done
