### ISSUE TITLE
Community Service

### ISSUE THREAD

**Issue by dexslab** [LADOJRP/server#164]
Some people have said when they do CS and they have to "clean" certain areas it does not allow them to clean even if they are within the highlighted circle for the CS.

---
This issue was created by `@lil cherry` in `#server-issues`.

**Comment by urban-z** [comment]
Ensure the user follows these steps:

1.) Reports to Probation Officer at courthouse (should map to it automatically)
2.) Signs in and picks "Clean Areas"
3.) Goes to area assigned and cleans

These areas can be large or small based on which one the system randomly picks
