### ISSUE TITLE
Cant load into the game

### ISSUE THREAD

**Issue by dexslab** [LADOJRP/server#169]
Everytime  I load into the game i crash straight away 4 times this has happened

---
This issue was created by `@DaveB` in `#server-issues`.

**Comment by Dbray002757** [comment]
![image](https://github.com/LADOJRP/server/assets/131198067/a8016a3c-4705-44ae-bdbb-5fb0857d290a)

**Comment by urban-z** [comment]
@Dbray002757 can you provide us with the log files?

**Comment by urban-z** [comment]
NO response
