### ISSUE TITLE
Commuinty Service

### ISSUE THREAD

**Issue by dexslab** [LADOJRP/server#173]
So whenever doing the jobs it's outlinded in orange and for my last one it wasn't there and I couldn't request a new job. I asked staff they didn't know and I think Alan had the same problem. I looked everywhere in the circle and I couldn't find it at all after looking for about 5-10 mins, AFTER all the jobs were done.

---
This issue was created by `@NOODLE` in `#server-issues`.

**Comment by urban-z** [comment]
Duplicate of #164
