### ISSUE TITLE
Cones

### ISSUE THREAD

**Issue by dexslab** [LADOJRP/server#177]
I am using the tapemenu to place down cones, however, when I do that nobody can see the cones which is annoying cause I try to shut down roads and it won't work because people drive right through. It's the same with the f10 menu.

---
This issue was created by `@spectrum9540` in `#server-issues`.

**Comment by ScottUK** [comment]
Players or NPCs can't see them and drive through them? I was using cones last week and players stopped for them.

**Comment by dexslab** [comment]
NPCs will do what ever they need to do to go over things please use F10 to properly setup a speed zone then setup the tape to avoid issues
