### ISSUE TITLE
Wrong speed

### ISSUE THREAD

**Issue by dexslab** [LADOJRP/server#179]
The new hud spedometer is not currently correct speed I have it on real time refresh rate and when im going 160 its telling me im going 258 and yes its in MPH

---
This issue was created by `@lenox7312` in `#server-issues`.

**Comment by dexslab** [comment]
This is a known issue i must inform the dev of the script as its broken and i cannot fix it.

**Comment by urban-z** [comment]
Resolved by Dex & Pablo
