### ISSUE TITLE
fire script

### ISSUE THREAD

**Issue by dexslab** [LADOJRP/server#18]
won’t work, says something about incorrect nill value

---
This issue was created by `@matt22` in `#server-issues`.

**Comment by dexslab** [comment]
Can you give me details in regards to what you are doing when this happens thanks

**Comment by nukeem1** [comment]
> Can you give me details in regards to what you are doing when this happens thanks

when you go to start fires for scenes it this pops up and say error and the spawn fires are not spawning [](url)
![image](https://user-images.githubusercontent.com/124907255/217863846-ecb0329e-abb4-4e9d-ae05-4f68aa11d47e.png)

**Comment by dexslab** [comment]
> > Can you give me details in regards to what you are doing when this happens thanks
> 
> when you go to start fires for scenes it this pops up and say error and the spawn fires are not spawning ![image](https://user-images.githubusercontent.com/124907255/217863846-ecb0329e-abb4-4e9d-ae05-4f68aa11d47e.png)

Can you give me the exact steps to reproduce this because i need to make sure i do it correctly to debug the problem

**Comment by JJohnson2x** [comment]
so when you do /startfire normal 2 2 it shows the script error

**Comment by dexslab** [comment]
Should be fixed now

**Comment by dexslab** [comment]
Confirmed fixed
