### ISSUE TITLE
Create Officer CAD Issue

### ISSUE THREAD

**Issue by barflesnorp** [LADOJRP/server#19]
When you create an officer from the Citizen tab it does not actually create an officer on the "My Officers" tab.

**Comment by dexslab** [comment]
You officer is created but it must be approved before you will have access to the LEO menu. Please contact your higher ups to get your LEO officer approved if you are actually part of a department. If you are not part of a department you will need to apply to gain access.

**Comment by Dev-CasperTheGhost** [comment]
this is a valid bug report. Will be fixing this today.

**Comment by Dev-CasperTheGhost** [comment]
This has been fixed in the latest version @dexslab :)

**Comment by barflesnorp** [comment]
@dexslab Now there is no Department or Divisions to select. Image linked below. Say's "No Options"

https://gyazo.com/520cb62d8060ce3db3f4c0dc21d14be9
