### ISSUE TITLE
marko mods

### ISSUE THREAD

**Issue by dexslab** [LADOJRP/server#195]
whenever I respawn a ped or change something my f9 weapons and peper spray go away whilst on duty, this is a bad feature and if it can It would be cool to get it fixed

---
This issue was created by `@klauff` in `#server-issues`.

**Comment by dexslab** [comment]
we will look into this but i am not sure if we can fix it

**Comment by urban-z** [comment]
I believe this is a native game function since you are essentially respawning the PED.. only happens when spawning new ped with VMENU MP PED.
