### ISSUE TITLE
Gas Pumps Aint Working

### ISSUE THREAD

**Issue by dexslab** [LADOJRP/server#199]
I have 100K in my inventory and the pump is stuck on 1.0L Ive tried this numerous times and end up here everytime.

---
This issue was created by `@davis0_0.` in `#server-issues`.

**Comment by Davis7738** [comment]
![2023-07-14 23_04_12-FiveM® by Cfx re - Los Angeles DOJRP (LADOJRP) _🚨Police_EMS_Fire🚨_ discord gg_](https://github.com/LADOJRP/server/assets/130861974/9e9b125a-d1bd-41e8-b737-3b6b75cdeaf3)

**Comment by dexslab** [comment]
Just relog current script is temp and this issue will be fixed with new script thanks
