### ISSUE TITLE
2016 Explorer

### ISSUE THREAD

**Issue by dexslab** [LADOJRP/server#20]
The lisence plate on this car is covered in blue just if it would get fixed would be nice

---
This issue was created by `@Chartier` in `#server-issues`.

**Comment by dexslab** [comment]
Can you post a pic of what you mean so we can look into it

**Comment by Chartier22** [comment]
![Screenshot_20230214_070120](https://user-images.githubusercontent.com/125144633/218890496-0210bc4c-da86-4640-8841-910fe7b48f5d.png)

**Comment by dexslab** [comment]
@sourdirt Have you looked into this

**Comment by CaptainWiley** [comment]
Assigned this to myself will look into a fix

**Comment by urban-z** [comment]
@bigdevryan -- Since Wiley is no longer a vehicle dev, can you take this over?

**Comment by urban-z** [comment]
@bigdevryan any updates sir?

**Comment by bigdevryan** [comment]
> @bigdevryan any updates sir?

my fault never saw dis dont be checkin my email

**Comment by urban-z** [comment]
@bigdevryan close as we have new pack
