### ISSUE TITLE
Taxi Job Glitch

### ISSUE THREAD

**Issue by dexslab** [LADOJRP/server#232]
The Sandy Shores Taxi Job sent me here (https://cdn.discordapp.com/attachments/840497555724566538/1138456436112883713/image.png) but the blip to pick up the person is here in the middle of the river...? And as well, I don't know if it's meant to be like this, but the people don't get in my car just levitate wierdly and then the job properly begins).

---
This issue was created by `@C. Hunter` in `#server-issues`.

**Comment by urban-z** [comment]
Fixed and moved location
