### ISSUE TITLE
Pre-existing Interiors/Teleport Blips from the old Real Estate System

### ISSUE THREAD

**Issue by dexslab** [LADOJRP/server#239]
Around the map some of the old interiors & teleport blips from the previous Real Estate System exist, this means that sometimes you end up teleporting to the wrong interior rather than being able to view the actual one of the house, you can get launched under the map into the abyss where no interior exists any longer or you could be delivering packages i.e Amazon job, and can't complete it easily because you get spawned underneath the map every time you press E. It may not be an easy thing to fix, but it may relieve some stress on the server (from no longer having the old interiors in-game).

---
This issue was created by `@C. Hunter` in `#server-issues`.

**Comment by HunterACRD** [comment]
42.82, 1852.02, 22.83
Motel Doors @ 939
Front Door of Larry's RV Sales @ 940

**Comment by urban-z** [comment]
fixed
