### ISSUE TITLE
1970 Boss 302 Mustang (boss302) Broken

### ISSUE THREAD

**Issue by dexslab** [LADOJRP/server#242]
The vehicle customization options have disappeared, and no longer work in the mod menu. It was just engine stuff I think but it's gone.

---
This issue was created by `@C. Hunter` in `#server-issues`.

**Comment by HunterACRD** [comment]
Same with this vehicle 'fnfrx7'

**Comment by HunterACRD** [comment]
And 'accord11'

**Comment by bigdevryan** [comment]
fixed
