### ISSUE TITLE
Car Boosting

### ISSUE THREAD

**Issue by dexslab** [LADOJRP/server#250]
When going to the Car Boosting Ped (At a certain location that I've found) when you click on 'Get Job' there is a pop-up that says go find this car, but it doesn't put anywhere in your mini-map to get that car.

---
This issue was created by `@C. Hunter` in `#server-issues`.

**Comment by HunterACRD** [comment]
(This bug is fixed so this part of the script is mostly functional now - there is a few slight other bugs though: Sometimes the mission randomly cancels requiring you to log out, and sometimes the chop body bit doesn't appear so you can't complete the mission and have to relog).

**Comment by dexslab** [comment]
This will be looked into today

**Comment by barflesnorp** [comment]
> 

I noticed that when someone else gets to the car before you, it will then cancel the mission and then you will have to relog in order to get a new contract. 

As far as the "chop body" bit I had this issue but figured out you need to look at the front windshield with the third eye and it comes up.

**Comment by HunterACRD** [comment]
I've just tried to look at the front windshield to chop the body, it doesn't appear to work. The issue on chopping the body appears to be entirely on the SUV's that it doesn't work, from my experience so far.
