### ISSUE TITLE
Gas Pumps

### ISSUE THREAD

**Issue by dexslab** [LADOJRP/server#270]
basically when you get gas, if you run out of money like at 11$ itll stop. If you get more money later, and go to refill itll stop at the amount it stopped at last time, so you'll have to relog to fix it

---
This issue was created by `@subilover09` in `#server-issues`.

**Comment by dexslab** [comment]
I will be fixing this with new vehicle script

**Comment by urban-z** [comment]
@dexslab I believe this is fix, correct.  Since you can now go negative when fueling?
