### ISSUE TITLE
LEO Breaching

### ISSUE THREAD

**Issue by dexslab** [LADOJRP/server#275]
LEO can only breach house with flashbangs which means only 1 leo can enter the house because if anyone else enters they can only enter with flashbang so the previous officer that breached ill be flashed can you make a option where th eother officers can breach without flashbangs to make it easier.

---
This issue was created by `@jacksmith00` in `#server-issues`.

**Comment by urban-z** [comment]
will be looking into this

**Comment by urban-z** [comment]
Closing..

User must breach. then let the other users in..  

Possibility to look at it and stop breach if other users in instance are cops..

**Comment by urban-z** [comment]
FIXED!!! I AM A GENIUS!!!!
