### ISSUE TITLE
After grabbing someone with Third Eye

### ISSUE THREAD

**Issue by dexslab** [LADOJRP/server#278]
After cuffing and grabbing someone with Third Eye you can no longer run fast without death and a adrev

---
This issue was created by `@lukass` in `#server-issues`.

**Comment by dexslab** [comment]
which grab is being used

**Comment by Dbray002757** [comment]
Hye dex me personally Ive used both grabs in the third eye the **Escort** and **Drag** and they both make me jog afterwards and not sprint which causes everyone to make a report and get killed and adrev again

**Comment by Dbray002757** [comment]
Heres a video for you

**Comment by barflesnorp** [comment]
> Heres a video for you https://clipchamp.com/watch/uX5q9uAyGbH

you're a champ thank you, just seeing this but yes it's any drag
