### ISSUE TITLE
Hands and Arms not changing

### ISSUE THREAD

**Issue by dexslab** [LADOJRP/server#280]
When Officers go and get their uniform, they won’t have arms on short sleeve uniforms or they will have clipping on the long sleeve uniforms. I believe this is because it’s not changing their hands and arms after they have purchased hands and arms from the clothing store. I have had Urban change the CHP numbers 3 times and these issues of clipping or having no arms continue.

---
This issue was created by `@lukass` in `#server-issues`.

**Comment by urban-z** [comment]
Resolved by returning to VMenu
