### ISSUE TITLE
K9 Broken (again)

### ISSUE THREAD

**Issue by dexslab** [LADOJRP/server#281]
K9 will not attack when aiming the LEO service weapon and pressing E the dog will run to the person and do absolutely nothing the pop up will show up for the attack however nothing happens.

---
This issue was created by `@benpitt` in `#server-issues`.

**Comment by urban-z** [comment]
@dexslab --> Is this related to something we need to ask the DEV about again? It was working, then i think we updated and it broke again.

**Comment by urban-z** [comment]
Fixed
