### ISSUE TITLE
/unitsrefresh

### ISSUE THREAD

**Issue by dexslab** [LADOJRP/server#282]
/unitsrefresh is not working so when we update people in cad they have to ait until next restart to access new uniforms nothing comes up when we type it in anymore

---
This issue was created by `@jacksmith00` in `#server-issues`.

**Comment by dexslab** [comment]
This is an issue with the uniform stuff not the unitsrefresh unless their rank is not being updated but if everything is saved then it should be updating the ranks as well

**Comment by urban-z** [comment]
@dexslab when they do /unitsrefresh it does not update any ranks.. just the employee list. So if you add a new employee, you are good. But if you change the rank, it doesnt update at all.

**Comment by dexslab** [comment]
`async function updateUnits() {
    const res = await getFromCad(`/admin/manage/units?includeAll=true`);
    for (let i = 0; i < res.data.units.length; i++) {
        const unit = res.data.units[i];
        //console.log(`got unit ${unit.citizen.name} ${unit.citizen.surname}`);
        const orgs = Object.keys(Orgs);
        for (let i = 0; i < orgs.length; i++) {
            const org = Orgs[orgs[i]];
            if (org.type != BUSINESS_TYPE.gov) {
                continue;
            }
            // console.log(
            //     `got unit ${unit.citizen.name} ${unit.citizen.surname} checking if ${orgs[
            //         i
            //     ].toUpperCase()}`,
            // );
            const deptId = org.id;
            if (deptId != unit.department?.valueId) {
                //console.log("not in this dept");
                continue;
            }
            // console.log(
            //     `got unit ${unit.citizen.name} ${unit.citizen.surname} added to ${
            //         Orgs[orgs[i]].display
            //     }`,
            // );
            Orgs[orgs[i]].employees.push({
                citizenId: unit.citizen.id,
                rank: unit.rank?.id,
                badgeNumber: unit?.badgeNumber,
                callSign: `${unit.callsign}-${unit.callsign2}`,
            });
        }
    }
    console.log("Unit refresh complete");
}`

That is the code for ranks it posts to the webhook grabs all units listed and their current rank and stores it in to a table. this table is updated every time unitsrefresh is done

**Comment by dexslab** [comment]
This cannot be confirmed
