### ISSUE TITLE
invoice system

### ISSUE THREAD

**Issue by dexslab** [LADOJRP/server#284]
Invoice system does not open or takes 5-10 minutes to open. Seen issue happen with many people

---
This issue was created by `@jitsulynx` in `#server-issues`.

**Comment by dexslab** [comment]
This is due to the requests made server side more persons on the longer it can take we are still working on optimization

**Comment by urban-z** [comment]
Unable to reproduce this issue sir.  Please provide more context.  or video.  /invoice immediately opened the menu for me in the main server.

**Comment by urban-z** [comment]
@dexslab I've been on when we have 80 people on and never had an issue like this
