### ISSUE TITLE
Rescue Basket

### ISSUE THREAD

**Issue by dexslab** [LADOJRP/server#288]
Rescue basket is not working, not sure what exactly its purpose it but it doesnt spawn in or attach to helicopters

---
This issue was created by `@masterkenobi.` in `#server-issues`.

**Comment by dexslab** [comment]
Requires certain Helicopters to be used we will look into it but i dont think this is a priority

**Comment by urban-z** [comment]
This works and is tested.. it is complicated to use a single pilot
