### ISSUE TITLE
Blips for fire and LEO are not working

### ISSUE THREAD

**Issue by FireGoose311** [LADOJRP/server#29]
So far they are intermittent. Have tried on duty/off duty and they will sometimes pop up and then disappear. Same report from several other FIRE/EMS online as well. On-going for at least an hour. Have not spoken to LEO to see if theyre experiencing the same issue.

**Comment by dexslab** [comment]
Blips are going to be updated eventually i have some plans so you must be patient thanks

**Comment by FireGoose311** [comment]
All good, just wanted to make sure you were aware. I love you.

**Comment by dexslab** [comment]
Staff and LEO/Fire blips will come with new vMenu for now im closing this
