### ISSUE TITLE
vehicle - Vehicle

### ISSUE THREAD

**Issue by urban-z** [LADOJRP/server#308]
the older tahoes handling is horrible undrivable allmost and the grill infront of the car is messed upp

 This issue was submitted by airblane via LADOJRP Main Discord @ https://discord.com/channels/714606988675252244/1158172795839184978/1196777786296238180

**Comment by urban-z** [comment]
@FaZePeen21 --> Please investigate

**Comment by FaZePeen21** [comment]
Reviewing

**Comment by urban-z** [comment]
Tahoe: 2011 tahoe

**Comment by urban-z** [comment]
@LADOJRP/vehicle-team what is the status?

**Comment by RealDevDavid** [comment]
there is no 11 tahoe.

**Comment by RealDevDavid** [comment]
Grill was fixed and it handles fine.
