### ISSUE TITLE
Vehicle - Mega Ram driver window is slanted and not working correctly

### ISSUE THREAD

**Issue by urban-z** [LADOJRP/server#319]
megaramcustom spawncode. The driver window is broken and not correctly placed

 This issue was submitted by bradk69 via LADOJRP Main Discord @ https://discord.com/channels/714606988675252244/1158172795839184978/1198123164673249340

**Comment by urban-z** [comment]
@LADOJRP/vehicle-team please work on this

**Comment by RealDevDavid** [comment]
Reviewing tonight

**Comment by RealDevDavid** [comment]
fixed

**Comment by urban-z** [comment]
If fixed and tested.  Close issueSent from my iPhoneOn Feb 15, 2024, at 15:46, David ***@***.***> wrote:﻿
fixed
