### ISSUE TITLE
Maps - Add Sandy Fire

### ISSUE THREAD

**Issue by urban-z** [LADOJRP/server#322]
Add SANDY FIRE to new GIT HUB when it is back online

**Comment by urban-z** [comment]
Map is added.

There is grass at sandy medical

**Comment by urban-z** [comment]
@JimmyMccann  --> Need you to look at this pretty please

**Comment by urban-z** [comment]
Added sandy to new DEDI :)

**Comment by JimmyMccann** [comment]
Need to put on hold until the Creator creates compatibility files

**Comment by urban-z** [comment]
CLOSING -- WILL REOPEN WHEN NEW UPDATE
