### ISSUE TITLE
Script - Store Robbery

### ISSUE THREAD

**Issue by urban-z** [LADOJRP/server#326]
The robbery scripts are not lining up to the register / computers

 This issue was submitted by urban_z via LADOJRP Main Discord @ https://discord.com/channels/714606988675252244/1158172795839184978/1198548507309641748

**Comment by dexslab** [comment]
Were the gabz 24/7s removed if so we need to revert location

**Comment by urban-z** [comment]
@dexslab yes they were upgraded to new stores, we need to realign all the spots

**Comment by urban-z** [comment]
Realigned all robberies and added new skill check as OX LIB is buggy as fuck
