### ISSUE TITLE
Vehicle - Cannot Exit vehicle after opening vMenu

### ISSUE THREAD

**Issue by urban-z** [LADOJRP/server#329]
Whenever I go into the vMenu while in a vehicle, for some reason it does not allow me to exit by pressing "Y" or my hotbind key on my keyboard. Also it sometimes locks the front brakes up on the vehicle I'm driving.

 This issue was submitted by spicy_weiner5498 via LADOJRP Main Discord @ https://discord.com/channels/714606988675252244/1158172795839184978/1198695048464846878

**Comment by dexslab** [comment]
Most likely u have enabled your seatbelt on accident
