### ISSUE TITLE
Broken/Glitched CAD

### ISSUE THREAD

**Issue by dexslab** [LADOJRP/server#33]
Myself and a number of other units have been unable to enter data/text into certain areas of the CAD (i.e Arrest Reports, Tickets etc) which means we're unable to actually log the charges we're filing against people.

---
This issue was created by `@C. Hunter` in `#server-issues`.

**Comment by Dev-CasperTheGhost** [comment]
This is a duplicate of #26. Please make sure to update the SnailyCAD fork to the latest @dexslab.

**Comment by dexslab** [comment]
> This is a duplicate of #26. Please make sure to update the SnailyCAD fork to the latest @dexslab.

![image](https://user-images.githubusercontent.com/1696130/219811893-6a393451-97ab-4ee0-bf02-1d3563212985.png)
