### ISSUE TITLE
Vehicle - New Fire Engine (Spawn Code "Velocity")

### ISSUE THREAD

**Issue by urban-z** [LADOJRP/server#337]
Needs LAFD Liveries for "Engine 1" through "Engine 5". Also needs lights programmed (non-ELS).

 This issue was submitted by firegoose1 via LADOJRP Main Discord @ https://discord.com/channels/714606988675252244/1158172795839184978/1200050712323833957

**Comment by urban-z** [comment]
@FaZePeen21 @AlanLADOJRP  was this done already?

**Comment by FaZePeen21** [comment]
This goes Epticz, he is our livery dev

**Comment by RealDevDavid** [comment]
@AlanLADOJRP

**Comment by RealDevDavid** [comment]
@AlanLADOJRP

**Comment by urban-z** [comment]
@RealDevDavid I need an ETA on this ASAP!

**Comment by urban-z** [comment]
@FireGoose311 -- does this still need its livery?

**Comment by FireGoose311** [comment]
@urban-z We had issues programming the lights. I recommend the lights get sorted before tackling the livery, as without lights the livery would be a waste of effort.

**Comment by urban-z** [comment]
@FireGoose311 what is the spawn code? And what is wrong with the lights?
