### ISSUE TITLE
script - Pusher amount of pay for product 
Counterfeit cash cleaner down

### ISSUE THREAD

**Issue by urban-z** [LADOJRP/server#339]
Pusher pays to little for product not even realistic 
Counterfeit cash cleaner is down

 This issue was submitted by luis.r000 via LADOJRP Main Discord @ https://discord.com/channels/714606988675252244/1158172795839184978/1200252942889013348

**Comment by dexslab** [comment]
Cleaners should be fixed permanently now

**Comment by urban-z** [comment]
@dexslab what was up with the cleaners?
