### ISSUE TITLE
Vehicle

### ISSUE THREAD

**Issue by urban-z** [LADOJRP/server#348]
Spawn code: lc500 Issue with spoiler floating about 5-10 meters behind the car - Lexus 2021 Issue

Issue with spoiler floating about 5-10 meters behind the car

 This issue was submitted by EzineVeNuM via LADOJRP Main Discord @ https://discord.com/channels/714606988675252244/1158172795839184978/1202373743658414180

**Comment by FaZePeen21** [comment]
Will review this, we may need to re do the donator packs due to them being unlocked and most cars having extra parts

**Comment by urban-z** [comment]
@RealDevDavid please ensure you update your tickets

**Comment by RealDevDavid** [comment]
This has been replaced
