### ISSUE TITLE
Vehicle - Audi A6

### ISSUE THREAD

**Issue by urban-z** [LADOJRP/server#357]
This issue was submitted by casheey via LADOJRP Main Discord @ https://discord.com/channels/714606988675252244/1158172795839184978/1205146822452969503

**Comment by urban-z** [comment]
@RealDevDavid is this one you removed?

**Comment by urban-z** [comment]
@RealDevDavid ????

**Comment by RealDevDavid** [comment]
It will be removed tonight and replaced
