### ISSUE TITLE
Script - Electrocardiograph Not Working

### ISSUE THREAD

**Issue by urban-z** [LADOJRP/server#365]
When the ECG Monitor is placed down and attached to a patient, nothing appears to happen. The monitor does not show visual feedback reflective of lead attachment nor audio queues of the ECG rythm or alarms, or access to options such as defibrilation.

 This issue was submitted by vulpinroid via LADOJRP Main Discord @ https://discord.com/channels/714606988675252244/1158172795839184978/1206419312567652392

**Comment by LADOMPrower** [comment]
Video of the issue here https://imgur.com/a/c725A0C

**Comment by urban-z** [comment]
REVERTING
