### ISSUE TITLE
Vehicle - EMS FPIU

### ISSUE THREAD

**Issue by urban-z** [LADOJRP/server#374]
ems2020fpiu handles like a boat and just rocks while braking and turning.

 This issue was submitted by klauff via LADOJRP Main Discord @ https://discord.com/channels/714606988675252244/1158172795839184978/1206813047646322698

**Comment by urban-z** [comment]
assigned to Moore

**Comment by RealDevDavid** [comment]
@urban-z whats the status on this?

**Comment by urban-z** [comment]
I assigned to you for an updateSent from my iPhoneOn Feb 15, 2024, at 15:42, David ***@***.***> wrote:﻿
@urban-z whats the status on this?

**Comment by urban-z** [comment]
@RealDevDavid I sent this to you all to look at.. why are you pinging me?

**Comment by RealDevDavid** [comment]
You put assigned to Moore.

**Comment by RealDevDavid** [comment]
This has been updated
