### ISSUE TITLE
guns not showing in shooting logs

### ISSUE THREAD

**Issue by dexslab** [LADOJRP/server#38]
The Weapon_tacticalrifle and weapon_heavyrifle dont show up on shooting logs when they are fired

---
This issue was created by `@King Fish` in `#server-issues`.

**Comment by DaPickle** [comment]
where do you spawn the weapons in at?

**Comment by KingFishez** [comment]
via the f1 menu--- weapon options--- spawn weapon by name

**Comment by dexslab** [comment]
Fixed
