### ISSUE TITLE
Script - Jail Jobs

### ISSUE THREAD

**Issue by urban-z** [LADOJRP/server#397]
While in 3rd eye to start a job in jail right when I clicked the interaction button to open the jobs menu it instantly closed

 This issue was submitted by bleusclues via LADOJRP Main Discord @ https://discord.com/channels/714606988675252244/1158172795839184978/1209862365844348978

**Comment by urban-z** [comment]
@C1tad31  please investigate this issue and report back

**Comment by C1tad31** [comment]
this isnt really an issue, if it closes automatically then you need to stand closer to the job npc it will close if you try to open it to far away from the npc
