### ISSUE TITLE
Script - County Employment/Job Center

### ISSUE THREAD

**Issue by urban-z** [LADOJRP/server#400]
**Approved Suggestion**
Employment center in county

On the steps
![image](https://github.com/LADOJRP/server/assets/129465098/9524c848-3bc7-475e-9361-46b8b4a71bbb)

**Comment by urban-z** [comment]
APPROVED BY AD/DIRECTOR

**Comment by C1tad31** [comment]
Job center added to the county church and waypoints are now sending players to county and city job start points respectively
