### ISSUE TITLE
Vehicle - Bumper of vehicle it’s messed up

### ISSUE THREAD

**Issue by urban-z** [LADOJRP/server#414]
I spawned in the vehicle and the bumper it’s far from the vehicle the spawn code it’s 650s

 This issue was submitted by harolddcp via LADOJRP Main Discord @ https://discord.com/channels/714606988675252244/1158172795839184978/1211022348354854922

**Comment by AlanLADOJRP** [comment]
This will be fixed by tonight

**Comment by urban-z** [comment]
@AlanLADOJRP status

**Comment by AlanLADOJRP** [comment]
This has been fixed
