### ISSUE TITLE
Vehicle - Ram Bar On 2018 Ford F-350

### ISSUE THREAD

**Issue by urban-z** [LADOJRP/server#415]
The rambar on the sdgf350 (2018 Ford F-350) falls off at the slightest touch or just randomely while you are driving.

 This issue was submitted by 1adam07 via LADOJRP Main Discord @ https://discord.com/channels/714606988675252244/1158172795839184978/1211045366640803880

**Comment by urban-z** [comment]
@AlanLADOJRP status

**Comment by AlanLADOJRP** [comment]
This has been fixed, and will be in the main server next restart.
