### ISSUE TITLE
Vehicles - Rays Debadge TICKET #30407

### ISSUE THREAD

**Issue by urban-z** [LADOJRP/server#423]
1. "ar8lb", -- Henry1902 personal car
2. "Prius", -- Ray Dono Car
3. "A1chrysler", -- Ray Dono
4. "defenderoffp", -- ray dono car
5. "trumpdodge", -- ray dono car
6. "wlpn", -- ray  personal car
7. "tractorsmall", -- ray  personal car
8. "79Offroad", -- ray  personal car
9. "rayescalade", -- ray  personal car
10. "00excursion", -- Ray L Dono Car
11. "kev", -- Ray Dono Car
12. "project8", -- Ray Dono Car
13. "lcphantom6x6", -- Ray dono car
14. "audir8lms2", -- Ray R8
15. "19ramoffroad", -- Ray Ram
16. "yacht4", -- Rays Yacht
17. "dotcro", -- Ray Dono Car
18. "f40", -- Ray Dono car
19. "raybronco", -- Rays civ bronco
20. "rayho", -- Rays honda od
21. "rmodx6", -- Ray dono car
22. "impala64", -- Rays car
23. "expmax20", -- Rays car
24. "richobs", -- Rays car
25. "bcexpress", -- ray dono car
26. "davidburb", -- ray dono car
27. "minif150long", -- ray dono car
28. "svjtt", -- ray dono car
29. "madwagon", -- ray dono car
30. "chevelle67", -- Rays car
31. "s15", -- Rays car
32. "chsub01", -- Rays 20th Dono Car
33. "H2", -- ray personal
34. "raytrucks", -- ray personal
35. "rsvr16", -- Henry1902 personal car
36. "dot3", -- Rays 22nd Dono Car
37. "dnh", -- Rays 23rd Dono Car
38. "t680", -- Rays 24th Dono Car
39. "sharkski", -- Rays 25th Dono Car
40. "fireae86", -- Rays 25th Persaonl
41. "GODzDRAGSKY", -- ray personal vehicle
42. "GODzDEERE6x6", -- ray personal vehicle
43. "TC00excV2", -- ray personal vehicle
44. "trig", -- ray personal vehicle
45. "mhx2", -- Rays Helicopter
46. "unarm", -- ray personal car
47. "uaz3159", -- ray personal car
48. "73venom", -- Ray Dono Car
49. "599xxevo", -- Fish's Ferrari
50. "gxrx7", -- Ray Dono Car
51. "17jamb", -- ray personal
52. "ftrailer", -- ray personal
53. "hydrasport53", -- ray personal
54. "fjcruiser12", -- ray personal
55. "rtruck", -- Ray Dono Car
56. "hilux2", -- Ray Dono Car
57. "eva", -- Ray Dono Car
58. "TCtaford08", -- ray tahoe
59. "PavementF450", -- ray f450
60. "jdramflat", --Ray Flatbed Ram
61. "Cade2ndGen", -- Ray dono truck
62. "fxxk", -- Ray dono car
63. "6.0Flatbedg", -- ray personal
64. "F250", -- Ray dono truck
65. "dragm2", -- Ray dono car
66. "sprintairstream", -- 2016 Mercedes Sprinter (Dex)
67. "sdliftedescalade", -- ray lifted escalade
68. "zaccgooseprius", -- ray lifted 1st gen ram dually
69. "a1chrysler", -- Chrysler
70. "tahoe71", -- Ray Tahoe
71. "godzcontslab", -- Ray
72. "a1dodge", -- Ray
73. "escladebyv", -- Ray
74. "gt63rgbsbyv", -- Ray

**Comment by urban-z** [comment]
@LADOJRP/vehicle-team - Once completed please let us know and the script team will add the TVs to them.

**Comment by RealDevDavid** [comment]
@urban-z We are aiming for tmrs restart however like 30-40 have been added which can be found in to do list

**Comment by urban-z** [comment]
@RealDevDavid where are we with this?

**Comment by AlanLADOJRP** [comment]
Done
