### ISSUE TITLE
Vehicle - LASD Ford Taurus Body Roll

### ISSUE THREAD

**Issue by urban-z** [LADOJRP/server#425]
The 2018 Ford Taurus with Rambar and Lightbar has body roll that causes flipping when turning with reasonable speed.
https://medal.tv/games/gta-v/clips/1XUVnrhPlkXvFw/d1337nG1wzBX?invite=cr-MSxjVVYsMTkzNzgzODQ5LA
This is the clip where it happens

 This issue was submitted by _1m4g1n3_w4g0n5_ via LADOJRP Main Discord @ https://discord.com/channels/714606988675252244/1158172795839184978/1212194879330066453

**Comment by urban-z** [comment]
@LADOJRP/vehicle-team any updates on this?

**Comment by FireGoose311** [comment]
> @LADOJRP/vehicle-team any updates on this?

No issue found. Per the clip, the vehicle likely hit a bump on the runway which caused it to roll. Drove it around the state for 15 minutes and could not replicate on normal roads at varying speeds.
