### ISSUE TITLE
Vehicle - Whitelist issue. spawn code escladebyv

### ISSUE THREAD

**Issue by urban-z** [LADOJRP/server#426]
The rear doors do not open on this vehicle. Players have to enter through the passenger front door and cycle seats to use the rear 8 seats. Thanks for your help.

 This issue was submitted by tencentslider via LADOJRP Main Discord @ https://discord.com/channels/714606988675252244/1158172795839184978/1212935467713040444

**Comment by AlanLADOJRP** [comment]
Thanks for reaching out to us about your concern. At this time, we are unable to fix this due to the way the original developer of the vehicle has locked the model. We apologize for any inconveniences this may have caused.
