### ISSUE TITLE
medical tablet

### ISSUE THREAD

**Issue by dexslab** [LADOJRP/server#43]
I cannot use my horn when someone is nearby because everytime I do it pulls up the medical tablet, I tried changing my horn keybind and it still does it.

---
This issue was created by `@Wiley` in `#server-issues`.

**Comment by dexslab** [comment]
Are you using a controller while driving :thinking:

**Comment by CaptainWiley** [comment]
This was meant to say headlights not horn, can we look into disabling the tablet while in-driver seat

**Comment by dexslab** [comment]
This should be fixed with next restart
