### ISSUE TITLE
Vehicle - car tornado when food in hand

### ISSUE THREAD

**Issue by urban-z** [LADOJRP/server#445]
i have a clip to provide better description - when i have a food item at the time a hot dog and i get into a drag R35 GTR the car turns into a tornado and starts to spin round fast

 This issue was submitted by north33 via LADOJRP Main Discord @ https://discord.com/channels/714606988675252244/1158172795839184978/1217563775348248688

**Comment by urban-z** [comment]
@AlanLADOJRP updates?

**Comment by AlanLADOJRP** [comment]
I can take a look again, but this seems like an issue with the food item?
