### ISSUE TITLE
Vehicle Handling - 2018 LEO Ford Taurus (Spawncode LASD9)

### ISSUE THREAD

**Issue by urban-z** [LADOJRP/server#448]
It flips when going around corners, even with minimal distruption. All other LEO Vehicles I've used have been able to go fast in similar areas without rolling

 This issue was submitted by _1m4g1n3_w4g0n5_ via LADOJRP Main Discord @ https://discord.com/channels/714606988675252244/1158172795839184978/1219819629757730897

**Comment by urban-z** [comment]
@FireGoose311 uodate?

**Comment by urban-z** [comment]
@FireGoose311 any updates?

**Comment by FireGoose311** [comment]
@urban-z Issue has been resolved, handling updated. The car no longer rolls when turning
