### ISSUE TITLE
vehicle - 2014 tahoe issue

### ISSUE THREAD

**Issue by urban-z** [LADOJRP/server#449]
a black wire type line is coming through the grill and is poking out about a foot from the car

 This issue was submitted by lowee4319 via LADOJRP Main Discord @ https://discord.com/channels/714606988675252244/1158172795839184978/1220080295009583184

**Comment by urban-z** [comment]
@AlanLADOJRP updates?

**Comment by AlanLADOJRP** [comment]
@ThatOneShmuck Assigned, completed
