### ISSUE TITLE
Script - Pickaxe

### ISSUE THREAD

**Issue by urban-z** [LADOJRP/server#455]
Whenever you are not using the pickaxe or it is just sitting in your inventory it continues to loose durability and eventually breaks.

 This issue was submitted by 1adam07 via LADOJRP Main Discord @ https://discord.com/channels/714606988675252244/1158172795839184978/1222287776959954984

**Comment by dexslab** [comment]
This is not a bug this is how pickaxes work they degrade over time so that u are required to purchase a new one. They are not that expensive. Current degrade time is 1 hour if not in use.
