### ISSUE TITLE
24/7 ATM Issue

### ISSUE THREAD

**Issue by MarkDavis16** [LADOJRP/server#458]
24/7 Interiors don't have the atms in the corner anymore but there is still an option to interact with one. Also the recording logs pop up when you go to the atm corner of the store.

https://github.com/LADOJRP/server/assets/99771937/7d9858a5-8029-4a2f-b06a-62fe027603bb

**Comment by urban-z** [comment]
We will need to remove each of the ATMs

**Comment by urban-z** [comment]
@MarkDavis16

**Comment by urban-z** [comment]
MLO updates has ATMs. ATMS working again
