### ISSUE TITLE
Vehicle - The 2 Back Doors on the escaladebyv do not open anymore

### ISSUE THREAD

**Issue by urban-z** [LADOJRP/server#461]
When Attempting to open the 2 back doors is wont allow you i have attempted both third eye and the personal vehicle option Before they did work i believe it might be bugged

 This issue was submitted by ethan5563 via LADOJRP Main Discord @ https://discord.com/channels/714606988675252244/1158172795839184978/1224145046987608084

**Comment by AlanLADOJRP** [comment]
This is not able to be fixed due to the vehicle being hard locked

**Comment by urban-z** [comment]
Alan close thisSent from my iPhoneOn Apr 4, 2024, at 09:43, AlanLADOJRP ***@***.***> wrote:﻿
This is not able to be fixed due to the vehicle being hard locked
