### ISSUE TITLE
F10 Prop menu

### ISSUE THREAD

**Issue by dexslab** [LADOJRP/server#51]
very wishy washy, works one day, then doesn’t work the next. Makes it hard to set up specific scenes.

---
This issue was created by `@R.Hallow` in `#server-issues`.

**Comment by dexslab** [comment]
ok will work on this

**Comment by urban-z** [comment]
@dexslab  - I think this is because the menu is disabled and you have to request HA ^ to turn it on.

**Comment by urban-z** [comment]
This has been turned on for Admin and LEO and FD now.

Ticket can be resolved

@dexslab

**Comment by urban-z** [comment]
This has been turned on for Admin and LEO and FD now.
