### ISSUE TITLE
vehicle - vehicle spawn code 2006f250g it doesnt connevt to any trailers

### ISSUE THREAD

**Issue by urban-z** [LADOJRP/server#522]
when im in the truck and try to attach a trailer to it, it does not let you attach it.

 This issue was submitted by usillywilly via LADOJRP Main Discord @ https://discord.com/channels/714606988675252244/1158172795839184978/1265454222124515418

**Comment by urban-z** [comment]
Anyone have an update on this?

**Comment by AlanLADOJRP** [comment]
Not something we are updating atm, if the original model doesn't come with trailer support it won't be added.
