### ISSUE TITLE
Vehicle - F450 Ambulance

### ISSUE THREAD

**Issue by urban-z** [LADOJRP/server#538]
The lights on the ambulance do not work. Upon turning them on they are completely disconnected from the car and hover in the air.

 This issue was submitted by qiskyz via LADOJRP Main Discord @ https://discord.com/channels/714606988675252244/1158172795839184978/1271927103394418780

**Comment by urban-z** [comment]
@AlanLADOJRP  please provide update

**Comment by PabloLado** [comment]
done
