### ISSUE TITLE
Vehicle - Adventure Pack duplicate vehicle

### ISSUE THREAD

**Issue by MarkDavis16** [LADOJRP/server#551]
In the adventure pack the "ATV" and "Sportsman" are the same vehicle just labeled differently. Only one is needed
![image](https://github.com/user-attachments/assets/6bee6802-c4e1-4659-9844-ab94b1c2fe3f)

**Comment by urban-z** [comment]
@MarkDavis16 have you spawned this in? they are different spawn codes in the menu

**Comment by urban-z** [comment]
disregard.. it did get added twice.. duplicate removed
