### ISSUE TITLE
script not perm on

### ISSUE THREAD

**Issue by dexslab** [LADOJRP/server#56]
The detective pack has not been perm turned on there for we need an exec to turn it on everyday

---
This issue was created by `@Sav` in `#server-issues`.

**Comment by CaptainWiley** [comment]
This needs to be added to the server.cfg

**Comment by dexslab** [comment]
@sourdirt can you add this to the vehicles.cfg for both dev and main thanks

**Comment by sourdirt** [comment]
@dexslab added detectivepack to dev and main server.cfg for vehicles after next push/restart.

**Comment by dexslab** [comment]
Fixed per sour
