### ISSUE TITLE
LASD Badge

### ISSUE THREAD

**Issue by dexslab** [LADOJRP/server#57]
LASD Badge is not in bags and parachutes like LAPDs. We need this updated so we can use a badge and body armor. Right now are badge takes up the body armor spot

---
This issue was created by `@Sav` in `#server-issues`.

**Comment by dexslab** [comment]
@JimmyMccann

**Comment by CaptainWiley** [comment]
This issue has been sent to @JimmyMccann and is pending/fixed.
