### ISSUE TITLE
Fire Script

### ISSUE THREAD

**Issue by dexslab** [LADOJRP/server#59]
The fire scripts are throwing an issue I have not seen before. This occurs when using /toggleautofires or /startfire.

---
This issue was created by `@Fire Truck` in `#server-issues`.

**Comment by FireGoose311** [comment]
![image](https://user-images.githubusercontent.com/125621476/229212434-86ec6c33-e3b6-484f-9f90-d833db7ef55d.png)

**Comment by dexslab** [comment]
Fixed
