### ISSUE TITLE
Script - Cargo Mission

### ISSUE THREAD

**Issue by MarkDavis16** [LADOJRP/server#595]
Cargo mission AI is not spawning and the mission can not be started from postal 18. 
![image](https://github.com/user-attachments/assets/e4573bd3-a2e8-40fb-9485-4b5c81e97e22)

**Comment by urban-z** [comment]
@MarkDavis16  I KNOW

**Comment by urban-z** [comment]
@MarkDavis16 maybe you should review tickets below before you create new ones
