### ISSUE TITLE
Script - Random Speakers Floating

### ISSUE THREAD

**Issue by MarkDavis16** [LADOJRP/server#596]
Speakers floating at the beach at postal 610 where the asgard mlo was. Items are seen by multiple people ![image](https://github.com/user-attachments/assets/4777857b-065e-4d6b-9f90-c251cd05a915)

**Comment by urban-z** [comment]
That is ASGARD left overs from the script that goes with it for the dj.. ill disable it.

**Comment by urban-z** [comment]
Disabled
