### ISSUE TITLE
LEO car wont spawn in when requested

### ISSUE THREAD

**Issue by dexslab** [LADOJRP/server#64]
Not to sure if it has been brought up before but the 2019 Silverado Spawncode code319silv. Its in the server It just wont spawn in when requested its been like this for a while and it would be nice to get it fixed since it is on the LAPD roster it would be nice to use as it is a good truck

---
This issue was created by `@Chris R` in `#server-issues`.

**Comment by urban-z** [comment]
Confirmed as not available.

**_Vehicle Spawn Code:_**
> code319silv

Pending response from someone with vehicle repo access to check file structure.

**Comment by urban-z** [comment]
@dexslab --> This has been confirmed.  It appears the YFT was removed from the pack.  Unsure if this was on purpose or accident.

**Comment by urban-z** [comment]
@dexslab this vehicle was removed from the pack
