### ISSUE TITLE
The jobs in prison dont work

### ISSUE THREAD

**Issue by dexslab** [LADOJRP/server#65]
the jobs let you start them but dont allow you to do them heres a clip of it https://youtu.be/xdPNESBoIuI the jobs dont work in prison

---
This issue was created by `@Ysf_Arb` in `#server-issues`.

**Comment by urban-z** [comment]
This issue is solved in a merge and pending release to the production environment.

**Comment by urban-z** [comment]
@dexslab please close. Duplicated issue. Fix was placed in recent merge. Shld be good after restart
