### ISSUE TITLE
Drug Bot

### ISSUE THREAD

**Issue by dexslab** [LADOJRP/server#70]
Drug bots currently do not give you drugs. Each time it says there is not enough space in your inventory. Believe it is due to it not knowing the new inventory and tries to feed into old which is gone. Tested it multiple times at each bot and each time it says "You cant carry all of that".

---
This issue was created by `@Bucky` in `#server-issues`.

**Comment by urban-z** [comment]
Validated as not working.  Confirmed with Buck via screen share. 

Looking at ox_inventory settings, I see that all the drugs are capitalized while all other inventory items are lowercase.  Might be the issue.

**Comment by dexslab** [comment]
This is not an issue you will need to stop carrying so much money on your person most likely each bill weights 1 gram so if u have more than 30k on you then I cannot carry anything else
