### ISSUE TITLE
FD Paleto

### ISSUE THREAD

**Issue by dexslab** [LADOJRP/server#71]
We can not unlock the side gate on the left. Not a massive issue. Just thought id let you know

---
This issue was created by `@DaveB` in `#server-issues`.

**Comment by Dbray002757** [comment]
![image](https://user-images.githubusercontent.com/131198067/232871192-febcef2d-db00-45c3-aad1-c52ee9e42ab8.png)

**Comment by dexslab** [comment]
May have forgot to add fire group we will fix it

**Comment by Dbray002757** [comment]
> May have forgot to add fire group we will fix it

Your amazing thank you :)

**Comment by dexslab** [comment]
Fixed this issue should be in once door lock script is restarted
