### ISSUE TITLE
Onduty Broke

### ISSUE THREAD

**Issue by dexslab** [LADOJRP/server#75]
The /onduty script is broken. Just says you have to be registered as an employee

---
This issue was created by `@DaveB` in `#server-issues`.

**Comment by Dbray002757** [comment]
![image](https://user-images.githubusercontent.com/131198067/234067772-2dcdac78-fb26-4267-9c08-c4da445c1baa.png)
Also if We do /onduty lapd or lasd says your on duty as FBI
