### ISSUE TITLE
EUP Bug

### ISSUE THREAD

**Issue by dexslab** [LADOJRP/server#96]
Hello I know its just me getting this issue but I was wondering if you know how to fix it. Some of my EUP doesnt load texture or pants ect for some

---
This issue was created by `@DaveB` in `#server-issues`.

**Comment by Dbray002757** [comment]
![image](https://user-images.githubusercontent.com/131198067/236715770-4cc20021-d725-40a0-b93e-70bf58c5b107.png) 

![image](https://user-images.githubusercontent.com/131198067/236715791-ca7fd85d-d6a0-45c5-a03b-1c11816beffa.png)

**Comment by Dbray002757** [comment]
Top is what it looks like for me and bottom his another players screen Ive reinstalled Fivem and deleted cache multiple times

**Comment by JimmyMccann** [comment]
@Dbray002757 Can i ask who the officer is in the outfit

**Comment by dexslab** [comment]
EUP has been updated this issue seems to be resolved
